services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "7002:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - TZ=Asia/Jakarta
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME:-e-plan-ai}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-rootpassword}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
