-- Migration: Alter dokumen_pdf table
ALTER TABLE dokumen_pdf
MODIFY COLUMN id BIGINT UNSIGNED AUTO_INCREMENT,
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
